apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone with the atlas-sa service account to
# read pods
kind: ClusterRoleBinding
metadata:
  name: atlas-binding
subjects:
- kind: ServiceAccount
  name: atlas-sa
  namespace: atlas
roleRef:
  kind: ClusterRole
  name: atlas
  apiGroup: rbac.authorization.k8s.io
